### ISSUE TITLE
ModuleNotFoundError: No module named 'minifier' on Python 3.10

### ISSUE THREAD

**Issue by imqwertyc** [rspivak/slimit#117]
I wanted to parse js and this error appeard

```
Traceback (most recent call last):
  File "/workspaces/some_project", line 5, in <module>
    from slimit.parser import Parser
  File "/home/codespace/.python/current/lib/python3.10/site-packages/slimit/__init__.py", line 27, in <module>
    from minifier import minify
ModuleNotFoundError: No module named 'minifier'
```
How to fix it

**Comment by indiofran** [comment]
i use `pip install git+https://github.com/rspivak/slimit.git#egg=slimit` to solve it
